cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@admin.admin
      logged_in: false
      name: admin
      password: $2b$12$YNNfUWSvRDEVSFyOuXUqZuSi4Iw2bALA04q20lCi3CE3bvEF5Cdpa
    dummy:
      email: dummy@dummy.dummy
      failed_login_attempts: 0
      logged_in: false
      name: dummy
      password: $2b$12$kGP94CoxW07nhp931hrbAeKExp5QrWFQQd1c0UnaV24a2RvsnkeJK
    test:
      email: test@test.test
      failed_login_attempts: 0
      logged_in: false
      name: test
      password: $2b$12$olnLcyNtLOelDkCWpPqYkeUDQ9NttQ76cvjog..6pfnwsXl1F4Kq6
pre-authorized:
  emails:
  - admin@admin.admin
